language: python
python:
  - "3.5"
install: 
  - pip install -q Django==1.10
  - pip install requests
  - pip install python-mysqldb
before_script:
  - cd app/myproject
script: python manage.py test
services:
  - mysql