models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
     command: bash -c "mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./myproject/wsgi.py && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata studenthousing/fixtures/db_init.json"
